version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  strapi:
    image: node:20
    working_dir: /srv/app
    command: >-
      bash -lc "npx create-strapi-app@latest cms --ts --no-run --skip-cloud --dbclient=postgres --dbhost=postgres --dbport=5432 --dbname=strapi --dbusername=strapi --dbpassword=strapi && cd cms && npm run develop"
    environment:
      STRAPI_TELEMETRY_DISABLED: "true"
      CI: "true"
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    volumes:
      - ./cms:/srv/app/cms

volumes:
  db_data:


